### ISSUE TITLE
Guide or wiki or forum?  Cannot play playlist...

### ISSUE THREAD

**Issue by tvadi** [ffplayout/ffplayout-frontend#77]
I have it installed from the Docker set up, loaded the web GUI, I can load a file, loop in playlist and that fills the day with that file but nothing plays in the viewer.  Clips viewer will play but not the player on the control page.  Bit of a newbie, looking for more of a guide or any insight.  Also, it looks like with the Docker set up it uses its own version on ffmpeg?  I need it to use the version I compiled that supports Decklink and libklvanc.  Any guidance would be great, thanks!

**Comment by jb-alvarado** [comment]
Personally I would recommend, not using the docket version. Better run the installer on a dedicated server or VM. Then you can also compile ffmpeg with decklink. The installer script uses this compiler script: https://github.com/jb-alvarado/compile-ffmpeg-osx-linux which support decklink to. The other lib you have to add by your self.

**Comment by tvadi** [comment]
Yes, I undid the docker and doing it all step by step..   Getting stuck at-


create .env file:

BASE_URL='http://example.org'
API_URL='/'

    in dev mode BASE_URL should be http://localhost:3000 and API_URL=http://localhost:8000

What do I do here?

**Comment by tvadi** [comment]
Just went with the installer (not docker)  Ran this config:
sudo ./install.sh
domain: localhost
https?  No
compile and install srs rtmp/hls server? yes
media path- /opt/tv-media
playlist path- /opt/playlists
multi channel setup (Y/n) : no
Do you wish to install nginx? (Y/n) : yes

How do I load the web page?  localhost just gives me the nginx page..  Maybe I should have not done nginx?  Or is ffplayout on a specific port?  Thanks!

**Comment by jb-alvarado** [comment]
Is this a clean and fresh machine? As I say IP needs the one from the machine.

**Comment by tvadi** [comment]
Ok, the machines IP, same as- settings> network, click gear..  192.168.1.xxx right?  

This was a fresh box, Ubuntu 20.04, but at first install I tried 10.50.0.1 ..I will start over with a fresh OS.  Is there any sort of way to uninstall or alter the config so I do not have to rebuild everything?  Thanks!

**Comment by jb-alvarado** [comment]
In yes, in terminal you can check IP with: `ip a`.

I just add a uninstall option to the installer. You can run this now with: `sudo ./install.sh --uninstall`

**Comment by tvadi** [comment]
With the new version you put up today, seems the installer got overwritten by the uninstaller..?

**Comment by tvadi** [comment]
I have it running now, web interface working, I can load MP4 files, loop playlist, save playlist, go a a different day and back to the current day and it loads the playlist good.  If I press the green play button - nothing happens.  Clicking the play button on a file in the playlist plays good in a pop up window but clicking the green "start playout service" button, no video plays in the viewer in the upper left of the page.  Under clocks it says "No clip is playing"..  Found the log page:  


Playout:
[2022-01-09 18:35:10,386] [ERROR]  ffmpeg contains no zmq filter!  Text messages will not work...
[2022-01-09 18:35:10,435] [DEBUG]  Encoder CMD: "ffmpeg -v level+error -hide_banner -nostats -re -thread_queue_size 160 -i pipe:0 -metadata service_name=Live Stream -metadata service_provider=example.org -metadata year=2022 -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset medium -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +global_header -f flv rtmp://localhost/live/stream"
[2022-01-09 18:35:10,438] [INFO]  Open: /home/matt/ffplaylist/2022/01/2022-01-09.json
[2022-01-09 18:35:10,442] [DEBUG]  List init
[2022-01-09 18:35:10,485] [INFO]  Play: /home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4
[2022-01-09 18:35:10,485] [DEBUG]  Decoder CMD: "ffmpeg -v level+error -hide_banner -nostats -ss 130.066 -i /home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4 -filter_complex [0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1] -filter_complex [0:a]anull,afade=in:st=0:d=0.5[aout1] -map [vout1] -map [aout1] -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 58982.4k -minrate 58982.4k -maxrate 58982.4k -bufsize 29491.2k -c:a s302m -strict -2 -ar 48000 -ac 2 -f mpegts -"
[2022-01-09 18:35:12,701] [ERROR]  Broken Pipe!
[2022-01-09 18:35:12,701] [DEBUG]  -------------------------------------------------------------------------------
[2022-01-09 18:35:12,701] [DEBUG]  error: "[Errno 32] Broken pipe"
[2022-01-09 18:35:12,701] [DEBUG]  delta: "0"
[2022-01-09 18:35:12,701] [DEBUG]  node: "{'source': '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4', 'in': 0, 'out': 166.233, 'duration': 166.233, 'category': '', 'seek': 130.066, 'begin': 66780.37599999999, 'number': 273, 'probe': , 'src_cmd': ['-ss', '130.066', '-i', '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4'], 'filter': ['-filter_complex', '[0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1]', '-filter_complex', '[0:a]anull,afade=in:st=0:d=0.5[aout1]', '-map', '[vout1]', '-map', '[aout1]']}"
[2022-01-09 18:35:12,701] [DEBUG]  dec_cmd: "['ffmpeg', '-v', 'level+error', '-hide_banner', '-nostats', '-ss', '130.066', '-i', '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4', '-filter_complex', '[0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1]', '-filter_complex', '[0:a]anull,afade=in:st=0:d=0.5[aout1]', '-map', '[vout1]', '-map', '[aout1]', '-pix_fmt', 'yuv420p', '-r', '25', '-c:v', 'mpeg2video', '-g', '1', '-b:v', '58982.4k', '-minrate', '58982.4k', '-maxrate', '58982.4k', '-bufsize', '29491.2k', '-c:a', 's302m', '-strict', '-2', '-ar', '48000', '-ac', '2', '-f', 'mpegts', '-']"
[2022-01-09 18:35:12,701] [DEBUG]  -------------------------------------------------------------------------------
[2022-01-09 18:35:13,921] [ERROR]  ffmpeg contains no zmq filter!  Text messages will not work...
[2022-01-09 18:35:13,969] [DEBUG]  Encoder CMD: "ffmpeg -v level+error -hide_banner -nostats -re -thread_queue_size 160 -i pipe:0 -metadata service_name=Live Stream -metadata service_provider=example.org -metadata year=2022 -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset medium -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +global_header -f flv rtmp://localhost/live/stream"
[2022-01-09 18:35:13,971] [INFO]  Open: /home/matt/ffplaylist/2022/01/2022-01-09.json
[2022-01-09 18:35:13,975] [DEBUG]  List init
[2022-01-09 18:35:14,019] [INFO]  Play: /home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4
[2022-01-09 18:35:14,019] [DEBUG]  Decoder CMD: "ffmpeg -v level+error -hide_banner -nostats -ss 133.6 -i /home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4 -filter_complex [0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1] -filter_complex [0:a]anull,afade=in:st=0:d=0.5[aout1] -map [vout1] -map [aout1] -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 58982.4k -minrate 58982.4k -maxrate 58982.4k -bufsize 29491.2k -c:a s302m -strict -2 -ar 48000 -ac 2 -f mpegts -"
[2022-01-09 18:35:16,356] [ERROR]  MediaProbe error in: "/home/matt/ffplaymedia/1080mp4cc8826881M544356H_2.mp4" Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '/home/matt/ffplaymedia/1080mp4cc8826881M544356H_2.mp4']' died with .
[2022-01-09 18:35:16,388] [INFO]  Got close command


Decoder:
[2022-01-09 18:35:12,687]  av_interleaved_write_frame(): Broken pipe
[2022-01-09 18:35:12,689]  av_interleaved_write_frame(): Broken pipe
[2022-01-09 18:35:12,689]  Error writing trailer of pipe:: Broken pipe
[2022-01-09 18:35:16,376]  Error writing trailer of pipe:: Broken pipe

Encoder:
[2022-01-09 18:35:05,630]  rtmp://localhost/live/stream: Connection refused
[2022-01-09 18:35:09,078]  [tcp @ 0x55a90213ac00] Connection to tcp://localhost:1935 failed: Connection refused
[2022-01-09 18:35:09,079]  [rtmp @ 0x55a902189dc0] Cannot open connection tcp://localhost:1935
[2022-01-09 18:35:09,079]  rtmp://localhost/live/stream: Connection refused
[2022-01-09 18:35:12,672]  [tcp @ 0x561078012540] Connection to tcp://localhost:1935 failed: Connection refused
[2022-01-09 18:35:12,673]  [rtmp @ 0x561077fd5dc0] Cannot open connection tcp://localhost:1935
[2022-01-09 18:35:12,673]  rtmp://localhost/live/stream: Connection refused


Thanks in advance!!!

**Comment by tvadi** [comment]
Pretty sure I can add libzmq (zmq filter) to my version of ffmpeg, are there any other libraries or items I need to add to ffmpeg?  What about all the broken pipes though?

**Comment by tvadi** [comment]
Added libzmq to ffmpeg and now the duration bar moves and player pages shows it is playing files but still nothing show in the player on that page, log still shows broken pipes..

Playout:
[2022-01-10 00:50:08,079] [DEBUG]  -------------------------------------------------------------------------------
[2022-01-10 00:50:08,079] [DEBUG]  error: "[Errno 32] Broken pipe"
[2022-01-10 00:50:08,079] [DEBUG]  delta: "0"
[2022-01-10 00:50:08,079] [DEBUG]  node: "{'source': '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4', 'in': 0, 'out': 166.233, 'duration': 166.233, 'category': '', 'seek': 17.673, 'begin': 89388.06399999902, 'number': 409, 'probe': , 'src_cmd': ['-ss', '17.673', '-i', '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4'], 'filter': ['-filter_complex', '[0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1]', '-filter_complex', '[0:a]anull,afade=in:st=0:d=0.5[aout1]', '-map', '[vout1]', '-map', '[aout1]']}"
[2022-01-10 00:50:08,079] [DEBUG]  dec_cmd: "['ffmpeg', '-v', 'level+error', '-hide_banner', '-nostats', '-ss', '17.673', '-i', '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4', '-filter_complex', '[0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1]', '-filter_complex', '[0:a]anull,afade=in:st=0:d=0.5[aout1]', '-map', '[vout1]', '-map', '[aout1]', '-pix_fmt', 'yuv420p', '-r', '25', '-c:v', 'mpeg2video', '-g', '1', '-b:v', '58982.4k', '-minrate', '58982.4k', '-maxrate', '58982.4k', '-bufsize', '29491.2k', '-c:a', 's302m', '-strict', '-2', '-ar', '48000', '-ac', '2', '-f', 'mpegts', '-']"
[2022-01-10 00:50:08,079] [DEBUG]  -------------------------------------------------------------------------------
[2022-01-10 00:50:09,471] [DEBUG]  Encoder CMD: "ffmpeg -v level+error -hide_banner -nostats -re -thread_queue_size 160 -i pipe:0 -metadata service_name=Live Stream -metadata service_provider=example.org -metadata year=2022 -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset medium -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +global_header -f flv rtmp://localhost/live/stream"
[2022-01-10 00:50:09,474] [INFO]  Open: /home/matt/ffplaylist/2022/01/2022-01-09.json
[2022-01-10 00:50:09,478] [DEBUG]  List init
[2022-01-10 00:50:09,521] [INFO]  Play: /home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4
[2022-01-10 00:50:09,521] [DEBUG]  Decoder CMD: "ffmpeg -v level+error -hide_banner -nostats -ss 21.415 -i /home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4 -filter_complex [0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1] -filter_complex [0:a]anull,afade=in:st=0:d=0.5[aout1] -map [vout1] -map [aout1] -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 58982.4k -minrate 58982.4k -maxrate 58982.4k -bufsize 29491.2k -c:a s302m -strict -2 -ar 48000 -ac 2 -f mpegts -"
[2022-01-10 00:50:11,677] [ERROR]  Broken Pipe!
[2022-01-10 00:50:11,677] [DEBUG]  -------------------------------------------------------------------------------
[2022-01-10 00:50:11,677] [DEBUG]  error: "[Errno 32] Broken pipe"
[2022-01-10 00:50:11,677] [DEBUG]  delta: "0"
[2022-01-10 00:50:11,677] [DEBUG]  node: "{'source': '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4', 'in': 0, 'out': 166.233, 'duration': 166.233, 'category': '', 'seek': 21.415, 'begin': 89388.06399999902, 'number': 409, 'probe': , 'src_cmd': ['-ss', '21.415', '-i', '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4'], 'filter': ['-filter_complex', '[0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1]', '-filter_complex', '[0:a]anull,afade=in:st=0:d=0.5[aout1]', '-map', '[vout1]', '-map', '[aout1]']}"
[2022-01-10 00:50:11,677] [DEBUG]  dec_cmd: "['ffmpeg', '-v', 'level+error', '-hide_banner', '-nostats', '-ss', '21.415', '-i', '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4', '-filter_complex', '[0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1]', '-filter_complex', '[0:a]anull,afade=in:st=0:d=0.5[aout1]', '-map', '[vout1]', '-map', '[aout1]', '-pix_fmt', 'yuv420p', '-r', '25', '-c:v', 'mpeg2video', '-g', '1', '-b:v', '58982.4k', '-minrate', '58982.4k', '-maxrate', '58982.4k', '-bufsize', '29491.2k', '-c:a', 's302m', '-strict', '-2', '-ar', '48000', '-ac', '2', '-f', 'mpegts', '-']"
[2022-01-10 00:50:11,677] [DEBUG]  -------------------------------------------------------------------------------
[2022-01-10 00:50:12,967] [DEBUG]  Encoder CMD: "ffmpeg -v level+error -hide_banner -nostats -re -thread_queue_size 160 -i pipe:0 -metadata service_name=Live Stream -metadata service_provider=example.org -metadata year=2022 -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset medium -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +global_header -f flv rtmp://localhost/live/stream"
[2022-01-10 00:50:12,969] [INFO]  Open: /home/matt/ffplaylist/2022/01/2022-01-09.json
[2022-01-10 00:50:12,974] [DEBUG]  List init
[2022-01-10 00:50:13,019] [INFO]  Play: /home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4
[2022-01-10 00:50:13,019] [DEBUG]  Decoder CMD: "ffmpeg -v level+error -hide_banner -nostats -ss 24.91 -i /home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4 -filter_complex [0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1] -filter_complex [0:a]anull,afade=in:st=0:d=0.5[aout1] -map [vout1] -map [aout1] -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 58982.4k -minrate 58982.4k -maxrate 58982.4k -bufsize 29491.2k -c:a s302m -strict -2 -ar 48000 -ac 2 -f mpegts -"
[2022-01-10 00:50:15,166] [ERROR]  Broken Pipe!
[2022-01-10 00:50:15,166] [DEBUG]  -------------------------------------------------------------------------------
[2022-01-10 00:50:15,166] [DEBUG]  error: "[Errno 32] Broken pipe"
[2022-01-10 00:50:15,166] [DEBUG]  delta: "0"
[2022-01-10 00:50:15,166] [DEBUG]  node: "{'source': '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4', 'in': 0, 'out': 166.233, 'duration': 166.233, 'category': '', 'seek': 24.91, 'begin': 89388.06399999902, 'number': 409, 'probe': , 'src_cmd': ['-ss', '24.91', '-i', '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4'], 'filter': ['-filter_complex', '[0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1]', '-filter_complex', '[0:a]anull,afade=in:st=0:d=0.5[aout1]', '-map', '[vout1]', '-map', '[aout1]']}"
[2022-01-10 00:50:15,166] [DEBUG]  dec_cmd: "['ffmpeg', '-v', 'level+error', '-hide_banner', '-nostats', '-ss', '24.91', '-i', '/home/matt/ffplaymedia/1080mp4cc8826881M544356H.mp4', '-filter_complex', '[0:v]fps=25,scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[vout1]', '-filter_complex', '[0:a]anull,afade=in:st=0:d=0.5[aout1]', '-map', '[vout1]', '-map', '[aout1]', '-pix_fmt', 'yuv420p', '-r', '25', '-c:v', 'mpeg2video', '-g', '1', '-b:v', '58982.4k', '-minrate', '58982.4k', '-maxrate', '58982.4k', '-bufsize', '29491.2k', '-c:a', 's302m', '-strict', '-2', '-ar', '48000', '-ac', '2', '-f', 'mpegts', '-']"
[2022-01-10 00:50:15,167] [DEBUG]  -------------------------------------------------------------------------------



Decoder:
[2022-01-10 00:53:39,458]  av_interleaved_write_frame(): Broken pipe
[2022-01-10 00:53:39,458]  Error writing trailer of pipe:: Broken pipe
[2022-01-10 00:53:42,893]  av_interleaved_write_frame(): Broken pipe
[2022-01-10 00:53:46,120]  av_interleaved_write_frame(): Broken pipe
[2022-01-10 00:53:49,420]  av_interleaved_write_frame(): Broken pipe
[2022-01-10 00:53:52,805]  av_interleaved_write_frame(): Broken pipe
[2022-01-10 00:53:56,246]  av_interleaved_write_frame(): Broken pipe
[2022-01-10 00:53:59,992]  av_interleaved_write_frame(): Broken pipe
[2022-01-10 00:54:03,431]  av_interleaved_write_frame(): Broken pipe


Encoder:
[2022-01-10 00:54:25,051]  rtmp://localhost/live/stream: Connection refused
[2022-01-10 00:54:28,503]  [tcp @ 0x55f4a5fcd280] Connection to tcp://localhost:1935 failed: Connection refused
[2022-01-10 00:54:28,504]  [rtmp @ 0x55f4a5fdf440] Cannot open connection tcp://localhost:1935
[2022-01-10 00:54:28,504]  rtmp://localhost/live/stream: Connection refused
[2022-01-10 00:54:31,876]  [tcp @ 0x558f047d44c0] Connection to tcp://localhost:1935 failed: Connection refused
[2022-01-10 00:54:31,876]  [rtmp @ 0x558f04808280] Cannot open connection tcp://localhost:1935
[2022-01-10 00:54:31,876]  rtmp://localhost/live/stream: Connection refused

Hoping to get decklink output but can test with the player page or wherever the output can be viewer.
Where and how do I set the output to ffmpeg/ decklink?   /etc/ffplayout/ffplayout.yml  ?  Also hoping to add .mpg and .TS to file types that can be used..  

Would

**Comment by jb-alvarado** [comment]
> With the new version you put up today, seems the installer got overwritten by the uninstaller..?

Yes, I had the exit state on the wrong place...

You only get an preview when you stream to a local rtmp server. At the moment it needs hls for the preview player and that will have a little delay around 30 seconds. Soon I will change that.
Because the decklink output will not match the settings you need for the preview, you have to compress the output two times. one for the preview and one for the decklink.

your output settings could look like:

```YAML
    ffmpeg_param: >-
        -c:v libx264
        -crf 23
        -x264-params keyint=50:min-keyint=25:scenecut=-1
        -maxrate 1300k
        -bufsize 2600k
        -preset medium
        -profile:v Main
        -level 3.1
        -c:a aac
        -ar 44100
        -b:a 128k
    stream_output: >-
        -flags +global_header
        -f flv rtmp://localhost/live/stream
        -pix_fmt uyvy422
        -vcodec v210
        -f decklink "DeckLink SDI 4K"
```
For that you have to install the srs rtmp server.

**Comment by tvadi** [comment]
Ok, thanks for the info.  I do not need preview although it would be nice, main thing is just playing out the decklink..  I entered the parameters you gave into the playout config but nothing is playing out the decklink.  Here is the short sample file I have looped in the playlist-  
[https://www.dropbox.com/s/ujyna1dx3bhs7p4/720ts_6DK01H_tru720og.ts?dl=0](url)
MediaInfo:
ormat                                   : MPEG-TS
File size                                : 199 MiB
Duration                                 : 3 min 12 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 8 665 kb/s

Video
ID                                       : 4096 (0x1000)
Menu ID                                  : 1 (0x1)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : 4:2:2@High
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : M=3, N=15
Codec ID                                 : 2
Duration                                 : 3 min 11 s
Bit rate mode                            : Constant
Bit rate                                 : 7 849 kb/s
Maximum bit rate                         : 8 000 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 59.940 (60000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:2
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.142
Time code of first frame                 : 00:00:10;00
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Closed
Stream size                              : 179 MiB (90%)

Audio
ID                                       : 4097 (0x1001)
Menu ID                                  : 1 (0x1)
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 2
Codec ID                                 : 3
Duration                                 : 3 min 11 s
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Frame rate                               : 41.667 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 8.78 MiB (4%)
Language                                 : English

**Comment by tvadi** [comment]
Ok thanks.  Already have ffmpeg playing out the decklink directly good with the ffmpeg line I listed above.. I guess that's why I was hoping I could just copy those settings over to ffplayout as I do not need rtmp at all but I will try as you say.  Does ffplayout play directly out ffmpeg or does everything go get "processed" with rtmp or other process?  I am worried about loosing my closed captions if processing/ transcoding it happening..  Thanks!

**Comment by jb-alvarado** [comment]
ffplayout will [process](https://github.com/ffplayout/ffplayout_engine/wiki) all input files. That's the only way to prevent A/V sync problems.

**Comment by tvadi** [comment]
Ok, just wanted to be sure ffplayout wasn't sending everything though rtmp and then out to ffmpeg or something like that.  Thanks for all your help in this, bit of a newbie..

**Comment by tvadi** [comment]
Ran install on a fresh Ubuntu 20.04.  Seems the option in the installer to compile ffmpeg does not install ffmpeg, maybe it is just asking if you want to compile..  As is, you must compile on your own to make it work, installing from the ubuntu app search gives a version with no ffprobe and installing in terminal lacks libfdk-aac.  I was able to get a version playing good with these libs plus the ones I need for Decklink and captions..

`
  --enable-gpl \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libsvtav1 \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree \
  --enable-libzmq\`

Log is no longer getting errors, just getting:
[2022-01-11 00:55:49,445] [DEBUG]  Encoder CMD: "ffmpeg -v level+error -hide_banner -nostats -re -thread_queue_size 160 -i pipe:0 -metadata service_name=Live Stream -metadata service_provider=example.org -metadata year=2022 -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset medium -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +global_header -f flv rtmp://localhost/live/stream"

I have everything set as default from the install but added .TS extension (playing a 720.ts file) and start time 00:00:00.  Not trying to do anything with Decklink, just view in VLC but fails to play when loading : rtmp://localhost/live/stream
VLC log says: avcodec error: Failed to open rtmp://localhost/live/stream: Connection refused
MPV also fails to load stream.  Is there something I am doing wrong or a better way to view the rtmp stream?  In installed the srs and the nginx server in the installer, is there something else I need to install? Thanks!

**Comment by jb-alvarado** [comment]
The installer and the engine had still some errors. Hopefully they are fixed now. If you want to compile your one ffmpeg, do it before running the installer and check that you are using the last version from ffmpeg and the zmq lib.

**Comment by tvadi** [comment]
Still getting VLC error: avcodec error: Failed to open rtmp://localhost/live/stream: Connection refused
I have codecs installed via:  sudo apt install ubuntu-restricted-extras    ...Also is there a specific version of node.js needed?  I have version 10 that you get when running:  sudo apt-get install npm 
With the newest version of the installer today it seems like we lost the logging.

**Comment by jb-alvarado** [comment]
You should run the installer.sh in a fresh and clean VM, minimum Ubuntu 20.04 /debian 10. Then you don't need to install npm, it will install everything.

For playing with VLC you need the address: ` rtmp://[IP from VM]/live/stream`

**Comment by tvadi** [comment]
I have a dedicated test server, no VM.  Tried again, fresh install of Ubuntu 20.04 (minimal), built ffmpeg fine, did not install npm, ran the latest ffplayout installer, I get 
`2022-01-11 22:26:09 (6.58 MB/s) - ‘v3.1.0.tar.gz’ saved [1212498]

bash: npm: command not found
bash: npm: command not found

------------------------------------------------------------------------------
installation done...
------------------------------------------------------------------------------
`
When I go to load the web UI on my local address, I get:

404 Not Found
nginx/1.18.0 (Ubuntu)

In var/log/nginx the log says:

`2022/01/11 22:26:09 [notice] 50401#50401: signal process started
2022/01/11 22:27:37 [error] 50403#50403: *1 "/var/www/ffplayout-frontend/dist/index.html" is not found (2: No such file or directory)`

Looks like it did not make the www/ffplayout-frontend/dist folder and contents..  Going to try again with a non-minimal Ubuntu, thought I needed minimal as I thought normal auto installed ffmpeg and I want my own version. Will report back but thinking it is something else..

**Comment by tvadi** [comment]
Still the same results as above with normal or minimal Ubuntu..

**Comment by jb-alvarado** [comment]
Did you run?:
- `git clone https://github.com/ffplayout/ffplayout-installer.git`
- `cd ffplayout-installer`
- `./install.sh`
- domain: machines ip
- nginx: yes
- https: no
- ffmpeg: yes
- srs: yes
- channels: no

**Comment by tvadi** [comment]
Yes, I did exactly that, only difference is I already had ffmpeg installed so that option did not show.  Installer also did not ask to do nginx.  I did uninstall nginx and uninstall ffplayout before running the installer again.  I will try again on a fresh ubuntu 20.04 without ffmpeg installed.

**Comment by tvadi** [comment]
Should I try a dummy domain instead of IP?  Does it work like that?

**Comment by jb-alvarado** [comment]
You need a domain name or IP which is reachable over the network. If you are using a firewall then port 80 should be open.

**Comment by tvadi** [comment]
I am just testing all on one Ubuntu 20.04 box, locally.

**Comment by jb-alvarado** [comment]
Then maybe localhost should work also.

When this is your workstation I would recommend to use KVM and install everything in a VM. With this you can add a snapshopt before install anything, so you can also swap back to a fresh and clean system.

**Comment by tvadi** [comment]
Fresh Ubuntu 20.04 ran the installer, needed curl, installed that and let the installed do its version on ffmpeg but the installer never asked to install nginx like previous installers did.   Looks like nginx did not get installed.
`bash: npm: command not found
bash: npm: command not found
cp: cannot create regular file '/etc/nginx/sites-available/': No such file or directory
sed: can't read /etc/nginx/sites-available/ffplayout.conf: No such file or directory
sed: can't read /etc/nginx/sites-available/ffplayout.conf: No such file or directory
ln: target '/etc/nginx/sites-enabled/' is not a directory: No such file or directory
Failed to reload nginx.service: Unit nginx.service not found.
installation done...
`
Also - sudo ./install.sh –uninstall    does not ask to uninstall, it brings you to the install questions.

**Comment by jb-alvarado** [comment]
Yes, I see...I mess up again the installer...
